export const TYPES = {
    SENDFORM: 'SENDFORM',
    SENDFORMWITHCHANGES: 'SENDFORMWITHCHANGES',
    DELETEFORM: 'DELETEFORM',
    DELETEROW: 'DELETEROW',
    EDITROW: 'EDITROW',
    DETECTCHANGES: 'DETECTCHANGES',
    DATAOFLOCALSTORAGE: 'DATAOFLOCALSTORAGE',
};